#!/bin/bash

STAGED_JS=$(git diff --cached --name-only --diff-filter=ACM | grep -E ".js(x|(-next)){0,1}$");
STAGED_SASS=$(git diff --cached --name-only --diff-filter=ACM | grep -E ".((sa)|(sc)|c)ss$");
ESLINT=$(which eslint);
SASSLINT=$(which sass-lint);

if [ -z "$STAGED_JS" ] && [ -z "$STAGED_SASS" ];
then
  exit 0
fi

if [ ! -x "$ESLINT" ];
then
    printf "\033[41mPlease install ESlint\033[0m (npm i -g eslint)\n"
    exit 1
fi

if [ ! -x "$SASSLINT" ];
then
    printf "\033[41mPlease install Sass Lint\033[0m (npm install -g sass-lint)\n"
    exit 1
fi

VALIDJS=true

if [ ! -z "$STAGED_JS" ];
then
    printf "\nValidating JavaScript files:\n"

    for FILEJS in $STAGED_JS;
    do
        "$ESLINT" "$FILEJS"

        if [ "$?" == 0 ];
        then
            VALIDJS=false
        fi
    done
fi

VALIDSASS=true

if [ ! -z "$STAGED_SASS" ];
then
    printf "\nValidating SASS files:\n"

    for FILESASS in $STAGED_SASS;
    do
        printf "$SASSLINT"
        "$SASSLINT" "$FILESASS" "--verbose --no-exit"

        if [[ "$?" != 0 ]];
        then
            VALIDSASS=false
        fi
    done
fi

if [ "$VALIDJS" == 0 ] && [ "$VALIDSASS" == 0 ];
then
  exit 0
fi

exit 1
